export default {
    APP_NAME: "PLAMCARE_WEB_CLIENT",

    // COMMON REDUCER TYPES
    RESET: "RESET",
    INIT_STORE: "INIT_STORE",
    RESET_STATE: "RESET_STATE",

    // LOGIN ACTIONS
    LOGIN: "LOGIN",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",

    // LOGOUT ACTIONS
    LOGOUT: "LOGOUT",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS"
};